"""empty message

Revision ID: e2fcbbbe2a5d
Revises: b58fd5652f4b
Create Date: 2023-12-18 17:13:27.553252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fcbbbe2a5d'
down_revision = 'b58fd5652f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('speciality', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('license_no', sa.String(), nullable=False))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['license_no'])
        batch_op.drop_constraint('doctors_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('years_of_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('doctors_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('license_no')
        batch_op.drop_column('speciality')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
