"""description of change

Revision ID: ea3b8a3bdad4
Revises: e2fcbbbe2a5d
Create Date: 2023-12-22 12:43:07.643836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3b8a3bdad4'
down_revision = 'e2fcbbbe2a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('speciality', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('profile_picture_uploaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('license_no', sa.String(), nullable=False))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['license_no'])
        batch_op.drop_constraint('doctors_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('doctors_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('license_no')
        batch_op.drop_column('profile_picture_uploaded')
        batch_op.drop_column('speciality')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
